### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by b4daz** [ByEvidencias/ByLFFUI#1]
;I forgot to put if ($sender->hasPermission("")); and I put that the form would open directly if $sender is a player. 
I'll fix it at some point, I'm too lazy right now haha. It's not really a problem since the /lff command should be default, only some weirdo would put it with permissions. 😳

**Comment by ByEvidencias** [comment]
Issue Fixed :)

**Comment by ByEvidencias** [comment]
Fixed

**Comment by b4daz** [comment]
Fixed
